### ISSUE TITLE
Switch image to use gradients instead of individual frames

### ISSUE THREAD

**Issue by nbitzz** [nbitzz/rocontrol#16]

**Comment by clustergrowling** [comment]
[commit: 119eb4d14b13495286f308b4d25f5c19fac9433d](https://github.com/nbitzz/rocontrol/commit/119eb4d14b13495286f308b4d25f5c19fac9433d) is showing some good progress, but scaling is not in, so that should be addressed

**Comment by nbitzz** [comment]
This already seems to be implemented fully. I've decided to close it
